__all__ = ["TokenType"]

class TokenType :
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, \
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, MOD, STAR, \
    QUESTION_MARK, COLON, \
    \
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, \
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, \
    \
    IDENTIFIER, STRING, NUMBER, \
    \
    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR, \
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, \
    BREAK, CONTINUE, \
    \
    EOF = range(44)

